// Catálogo de produtos, serviços e locação (mock estático)
window.TECHNOVA_DATA = {
  products: [
    { id:'p1', cat:'notebooks', name:'Notebook Gamer Nova X15', emoji:'💻', desc:'Intel i7, 16GB RAM, RTX 4060, SSD 512GB', price:6499.00, old:7299.00, rating:5, promo:true, featured:true },
    { id:'p2', cat:'notebooks', name:'Ultrabook Pro 14"', emoji:'💻', desc:'Ryzen 7, 16GB, SSD 1TB, leve e potente', price:5299.00, rating:4, featured:true },
    { id:'p3', cat:'pcs', name:'PC Workstation Quantum', emoji:'🖥️', desc:'i9, 32GB, RTX 4070, refrigeração líquida', price:9899.00, old:10999.00, rating:5, promo:true, featured:true },
    { id:'p4', cat:'pcs', name:'Mini PC Office', emoji:'🖥️', desc:'i5, 8GB, SSD 256GB, compacto', price:2199.00, rating:4 },
    { id:'p5', cat:'perifericos', name:'Teclado Mecânico RGB', emoji:'⌨️', desc:'Switches blue, ABNT2, retroiluminado', price:399.00, old:499.00, rating:5, promo:true, featured:true },
    { id:'p6', cat:'perifericos', name:'Mouse Gamer 16K DPI', emoji:'🖱️', desc:'Sensor óptico, 8 botões programáveis', price:249.00, rating:5 },
    { id:'p7', cat:'perifericos', name:'Headset Surround 7.1', emoji:'🎧', desc:'Microfone removível, drivers 50mm', price:329.00, rating:4, featured:true },
    { id:'p8', cat:'monitores', name:'Monitor 27" 144Hz QHD', emoji:'🖥️', desc:'IPS, 1ms, HDR, FreeSync', price:1899.00, old:2199.00, rating:5, promo:true },
    { id:'p9', cat:'monitores', name:'Monitor Ultrawide 34"', emoji:'🖥️', desc:'3440x1440, curvo, USB-C', price:3299.00, rating:5 },
    { id:'p10', cat:'redes', name:'Roteador Wi-Fi 6 AX5400', emoji:'📶', desc:'Tri-band, 6 antenas, mesh', price:799.00, rating:4 },
    { id:'p11', cat:'redes', name:'Switch Gigabit 24 portas', emoji:'🌐', desc:'Gerenciável, montagem em rack', price:1499.00, rating:5 },
    { id:'p12', cat:'armazenamento', name:'SSD NVMe 1TB', emoji:'💾', desc:'Leitura 7000MB/s, PCIe 4.0', price:599.00, old:749.00, rating:5, promo:true },
    { id:'p13', cat:'armazenamento', name:'HD Externo 2TB', emoji:'💽', desc:'USB 3.0, portátil, antichoque', price:449.00, rating:4 },
    { id:'p14', cat:'softwares', name:'Antivírus Premium 1 ano', emoji:'🛡️', desc:'5 dispositivos, proteção total', price:149.00, rating:4 },
    { id:'p15', cat:'softwares', name:'Office Suite 365', emoji:'📊', desc:'Licença anual + 1TB cloud', price:399.00, rating:5, featured:true },
    { id:'p16', cat:'softwares', name:'Sistema ERP PME', emoji:'💼', desc:'Licença mensal, multi-usuário', price:199.00, rating:4 },
  ],
  services: [
    { id:'s1', cat:'manutencao', name:'Formatação Completa', emoji:'🔧', desc:'Backup + instalação SO + drivers + softwares essenciais', price:120.00, rating:5, featured:true },
    { id:'s2', cat:'manutencao', name:'Manutenção Preventiva', emoji:'🛠️', desc:'Limpeza interna, troca de pasta térmica, diagnóstico', price:180.00, rating:5, featured:true },
    { id:'s3', cat:'manutencao', name:'Recuperação de Dados', emoji:'💾', desc:'HD/SSD com falha lógica ou física leve', price:450.00, rating:4 },
    { id:'s4', cat:'redes', name:'Instalação de Rede', emoji:'🌐', desc:'Configuração de roteador, Wi-Fi mesh, otimização', price:250.00, rating:5, featured:true },
    { id:'s5', cat:'redes', name:'Cabeamento Estruturado', emoji:'🔌', desc:'Projeto e instalação até 20 pontos (orçamento)', price:1500.00, rating:5 },
    { id:'s6', cat:'seguranca', name:'Auditoria de Segurança', emoji:'🔒', desc:'Análise de vulnerabilidades + relatório', price:890.00, rating:5, featured:true },
    { id:'s7', cat:'seguranca', name:'Backup em Nuvem (mensal)', emoji:'☁️', desc:'500GB criptografados, replicação diária', price:89.00, rating:4 },
    { id:'s8', cat:'consultoria', name:'Consultoria em TI', emoji:'💡', desc:'Hora técnica especialista (mín. 2h)', price:200.00, rating:5 },
    { id:'s9', cat:'consultoria', name:'Hospedagem de Site', emoji:'🌍', desc:'Plano anual, SSL, e-mail, 50GB SSD', price:349.00, rating:4, featured:true },
    { id:'s10', cat:'suporte', name:'Suporte Remoto', emoji:'🖥️', desc:'Atendimento via acesso remoto (1h)', price:80.00, rating:5 },
    { id:'s11', cat:'suporte', name:'Plano Suporte Mensal', emoji:'📞', desc:'Atendimento ilimitado em horário comercial', price:399.00, rating:5 },
  ],
  rentals: [
    { id:'r1', cat:'notebooks', name:'Notebook Corporativo', emoji:'💻', desc:'i5, 8GB, SSD 256GB — pronto para uso', price:80.00, unit:'dia', rating:5, featured:true },
    { id:'r2', cat:'notebooks', name:'Notebook Gamer Eventos', emoji:'🎮', desc:'i7, 16GB, RTX, ideal para LAN parties', price:150.00, unit:'dia', rating:5 },
    { id:'r3', cat:'projetores', name:'Projetor Full HD 4000 lumens', emoji:'📽️', desc:'HDMI, ideal para palestras', price:180.00, unit:'dia', rating:5, featured:true },
    { id:'r4', cat:'projetores', name:'Projetor 4K Cinema', emoji:'🎬', desc:'Alta luminosidade, lente zoom', price:450.00, unit:'dia', rating:5 },
    { id:'r5', cat:'servidores', name:'Servidor Rack Dual Xeon', emoji:'🗄️', desc:'64GB RAM, 4TB SSD, redundância', price:250.00, unit:'dia', rating:5, featured:true },
    { id:'r6', cat:'redes', name:'Roteador Wi-Fi Eventos', emoji:'📶', desc:'Wi-Fi 6, até 200 conexões simultâneas', price:90.00, unit:'dia', rating:4 },
    { id:'r7', cat:'redes', name:'Switch 48 portas PoE', emoji:'🌐', desc:'Para infraestrutura temporária', price:120.00, unit:'dia', rating:5 },
    { id:'r8', cat:'perifericos', name:'Kit Streaming Profissional', emoji:'🎥', desc:'Câmera + microfone + iluminação', price:220.00, unit:'dia', rating:5, featured:true },
  ],
  categories: {
    products: [
      { id:'notebooks', name:'Notebooks', icon:'💻' },
      { id:'pcs', name:'Desktops', icon:'🖥️' },
      { id:'perifericos', name:'Periféricos', icon:'⌨️' },
      { id:'monitores', name:'Monitores', icon:'🖼️' },
      { id:'redes', name:'Redes', icon:'📶' },
      { id:'armazenamento', name:'Armazenamento', icon:'💾' },
      { id:'softwares', name:'Softwares', icon:'🛡️' },
    ],
    services: [
      { id:'manutencao', name:'Manutenção', icon:'🔧' },
      { id:'redes', name:'Redes & Cabeamento', icon:'🌐' },
      { id:'seguranca', name:'Segurança', icon:'🔒' },
      { id:'consultoria', name:'Consultoria & Hosting', icon:'💡' },
      { id:'suporte', name:'Suporte', icon:'📞' },
    ],
    rentals: [
      { id:'notebooks', name:'Notebooks', icon:'💻' },
      { id:'projetores', name:'Projetores', icon:'📽️' },
      { id:'servidores', name:'Servidores', icon:'🗄️' },
      { id:'redes', name:'Redes', icon:'📶' },
      { id:'perifericos', name:'Periféricos', icon:'🎥' },
    ]
  }
};